server:
  port: 8500

#Mybatis 控制台打印SQL语句
logging:
  level:
    com.yue.websocket: debug
  file:
    name: logs/spring-boot-websocket.log
    max-size: 1024MB
    max-history: 7

spring:
  mvc:
    # 出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
    #不开启默认的资源处理(404异常可以获取到)
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver                      # mysql驱动包
      url: jdbc:mysql://47.107.120.118:3306/cardcloud?characterEncoding=utf-8&useUnicode=true&autoReconnect=true&autoReconnectForPools=true    # 数据库名称
      username: yue
      password: 12345678
      # 初始化时建立物理连接的个数
      initial-size: 50
      # 最大连接池数量
      max-active: 200
      # 最小连接池数量
      min-idle: 50
      # 获取连接时最大等待时间
      max-wait: 60000
  redis:
    database: 1             # Redis数据库索引（默认为0）
    host: 172.0.8.2         # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password: cardlan@2018        # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #spring.redis.pool.max-active=8
        max-active: 1000
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        #spring.redis.pool.max-wait=-1
        max-wait: -1
        ## 连接池中的最大空闲连接
        #spring.redis.pool.max-idle=8
        max-idle: 2
        ## 连接池中的最小空闲连接
        #spring.redis.pool.min-idle=0
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true